### ISSUE TITLE
Code of Conduct (link and page)

### ISSUE THREAD

**Issue by naps62** [groupbuddies/rubyconfpt-2015#10]

**Comment by johnny1337** [comment]
Should be available on the menu, under 'Where do you want to go'.

I'll work on the page soon.

**Comment by johnny1337** [comment]
![coc](https://cloud.githubusercontent.com/assets/2117730/7091862/1daac5e8-dfa5-11e4-94f0-6f1f5356d2b6.png)

Uploaded

**Comment by naps62** [comment]
This is now done
