### ISSUE TITLE
Button hover state

### ISSUE THREAD

**Issue by naps62** [groupbuddies/rubyconfpt-2015#6]
I need the hover style for all button types. Currently I only have it for the one on the main scene

**Comment by johnny1337** [comment]
![screen shot 2015-04-10 at 15 42 25](https://cloud.githubusercontent.com/assets/2117730/7090048/33589634-df98-11e4-974c-11bfe88bfb72.png)

I can add this to Zeplin as well.

**Comment by naps62** [comment]
Yes please
Also, where does the subscribe button on the nav menu fit on this?

**Comment by naps62** [comment]
Discussed in person
